### ISSUE TITLE
 no possibility to log in to integration

### ISSUE THREAD

**Issue by artirus** [Antoni-Czaplicki/vulcan-for-hassio#10]
```Szczegóły loga (ERROR)
Logger: aiohttp.server
Source: custom_components/vulcan/config_flow.py:37
First occurred: 10:02:09 (1 occurrences)
Last logged: 10:02:09
Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
result: Dict = await getattr(flow, method)(user_input)
File "/config/custom_components/vulcan/config_flow.py", line 37, in async_step_user
self._students = await client.get_students()
File "/usr/local/lib/python3.8/site-packages/vulcan/hebe/_hebe_client.py", line 61, in get_students
self._students = await Student.get(self._api)
File "/usr/local/lib/python3.8/site-packages/vulcan/hebe/model/_student.py", line 76, in get
return list(Student.load(student) for student in data)
File "/usr/local/lib/python3.8/site-packages/vulcan/hebe/model/_student.py", line 76, in <genexpr>
return list(Student.load(student) for student in data)
File "/usr/local/lib/python3.8/site-packages/vulcan/hebe/model/_serializable.py", line 49, in load
return to_model(cls, data)
File "/usr/local/lib/python3.8/site-packages/related/functions.py", line 104, in to_model
value = cls(**value)
File "<attrs generated init vulcan.hebe.model._student.Student>", line 5, in __init__
_setattr('pupil', __attr_converter_pupil(pupil))
File "/usr/local/lib/python3.8/site-packages/related/converters.py", line 40, in __call__
return to_model(self.cls, value)
File "/usr/local/lib/python3.8/site-packages/related/functions.py", line 104, in to_model
value = cls(**value)
File "<attrs generated init vulcan.hebe.model._pupil.Pupil>", line 13, in __init__
__attr_validator_login_value(self, __attr_login_value, self.login_value)
File "/usr/local/lib/python3.8/site-packages/attr/validators.py", line 35, in __call__
raise TypeError(
TypeError: ("'login_value' must be (<class 'str'>,) (got None that is a <class 'NoneType'>).", Attribute(name='login_value', default=NOTHING, validator=<instance_of validator for type (<class 'str'>,)>, repr=True, eq=True, order=True, hash=None, init=True, metadata=mappingproxy({'key': 'LoginValue'}), type=<class 'str'>, converter=<function str_if_not_none at 0x7f1b3d0563a0>, kw_only=False), (<class 'str'>,), None)```

**Comment by Antoni-Czaplicki** [comment]
This issue is API related, we are currently waiting for a new version to be released.

**Comment by Antoni-Czaplicki** [comment]
Ok, please try to update to the latest version (0.8.5) - it should fix that problem.
