### ISSUE TITLE
Error while adding integration

### ISSUE THREAD

**Issue by macieksonik** [Antoni-Czaplicki/vulcan-for-hassio#14]
I get error while trying to add integration. After putting token, symbol and PIN I get students names to choose (2). While choosing one of them (any, I've tried multiple times) I get "Unknown error".

```
Logger: aiohttp.server
Source: custom_components/vulcan/config_flow.py:97 
First occurred: 19:41:28 (7 occurrences) 
Last logged: 19:42:43

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 150, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 158, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/vulcan/config_flow.py", line 97, in async_step_select_student
    "login": self.account.user_login,
AttributeError: 'vulcanFlowHandler' object has no attribute 'account'
```

**Comment by Antoni-Czaplicki** [comment]
Fixed in [v0.9.1](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/releases/tag/0.9.1)
