### ISSUE TITLE
Sensory planu lekcji niedostępne

### ISSUE THREAD

**Issue by artirus** [Antoni-Czaplicki/vulcan-for-hassio#20]
Sensory planu lekcji na dzień dzisiejszy i jutrzejszy niedostępne.
Integracja odinstalowana, zainstalowana jeszcze raz przy wersji  10.3 obecnie 10.4
pozostałe sensory działają. W kalendarzu plan lekcji wyświetla się prawidłowo.

Błedy z logów:

Ten błąd pochodzi z niestandardowej integracji.
```
Logger: custom_components.vulcan
Source: helpers/update_coordinator.py:219
Integration: Uonet+ Vulcan (documentation, issues)
First occurred: 7:06:33 (1 occurrences)
Last logged: 7:06:33

Error fetching vulcan_timetable data: '40839'

Logger: homeassistant.components.sensor
Source: custom_components/vulcan/sensor.py:179
Integration: Sensor (documentation, issues)
First occurred: 7:06:40 (2 occurrences)
Last logged: 7:06:40


Error adding entities for domain sensor with platform vulcan
Error while setting up vulcan platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in _stringify_state
    if not self.available:
  File "/config/custom_components/vulcan/sensor.py", line 179, in available
    self.coordinator.data[f"lessons{self.tomorrow}"][
TypeError: 'NoneType' object is not subscriptable

```

![blad_2](https://user-images.githubusercontent.com/60752751/132464918-e0c6b16b-60df-48dd-ba71-713f59e9f750.jpg)
![blad vulcan1](https://user-images.githubusercontent.com/60752751/132464921-97218f55-d6ea-43aa-ae8f-93f144868803.jpg)

**Comment by Antoni-Czaplicki** [comment]
Błąd został naprawiony w najnowszej wersji

**Comment by artirus** [comment]
dziękuję bardzo Super robota
