### ISSUE TITLE
Integration not works after home assistant update to 2023.4

### ISSUE THREAD

**Issue by piotruscilko** [Antoni-Czaplicki/vulcan-for-hassio#42]
Hi, after las update integration not works - LOG:

Logger: homeassistant.helpers.entity
Source: components/calendar/__init__.py:345
First occurred: 16:52:43 (57 occurrences)
Last logged: 17:50:59

Update for calendar.vulcan_calendar_xxxxxxxxxxxxxxx fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 82, in validate
    raise vol.Invalid("Expected all values to have a timezone")
voluptuous.error.Invalid: Expected all values to have a timezone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected all values to have a timezone

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 763, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/vulcan/calendar.py", line 158, in async_update
    self._event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected all values to have a timezone

**Comment by xtronets** [comment]
To samo u mnie

**Comment by formiification** [comment]
Chyba coś w Vulcanie zmienili

**Comment by Antoni-Czaplicki** [comment]
Please try updating integration to the master branch

**Comment by mariuszxeno** [comment]
In my case, using the master branch, i.e.
8ed8941, removed the problem described in the thread, 
the calendar works, the logs are clean.

**Comment by Antoni-Czaplicki** [comment]
Great, i will push the release today
