### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by casper255** [Antoni-Czaplicki/vulcan-for-hassio#44]
All sensors are unavailable

Logger: homeassistant.helpers.entity
Source: helpers/aiohttp_client.py:67
First occurred: 12:23:16 (10 occurrences)
Last logged: 12:33:58

Update for calendar.vulcan_calendar_julia fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/config/custom_components/vulcan/calendar.py", line 138, in async_update
    events = await get_lessons(
  File "/config/custom_components/vulcan/fetch_data.py", line 13, in get_lessons
    async for lesson in await client.data.get_changed_lessons(
  File "/usr/local/lib/python3.10/site-packages/vulcan/data/_lesson.py", line 158, in get
    data = await api.helper.get_list(
  File "/usr/local/lib/python3.10/site-packages/vulcan/_api_helper.py", line 96, in get_list
    return await self._api.get(url, query, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/vulcan/_api.py", line 162, in get
    return await self._request("GET", url, body=None, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/vulcan/_api.py", line 126, in _request
    response = await r.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 67, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://lekcjaplus.vulcan.net.pl/dabrowagornicza/006320/api/mobile/schedule/changes/byPupil?unitId=13&pupilId=36042&periodId=15027&dateFrom=2023-05-14&dateTo=2023-05-21&lastId=-2147483648&pageSize=500&lastSyncDate=1970-01-01%2000%3A01%3A00')

**Comment by LukaszBogus** [comment]
Hi

I had the same. 
I tried deleted integration to repair it, and right now I can't log on to vulcan by HA. 

Logger: custom_components.vulcan.config_flow
Source: custom_components/vulcan/register.py:9
Integration: Uonet+ Vulcan ([documentation](https://github.com/Antoni-Czaplicki/vulcan-for-hassio), [issues](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/issues))
First occurred: 19:57:00 (2 occurrences)
Last logged: 19:59:39

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/vulcan/config_flow.py", line 71, in async_step_auth
    credentials = await register(
  File "/config/custom_components/vulcan/register.py", line 9, in register
    account = await Account.register(keystore, token, symbol, pin)
  File "/usr/local/lib/python3.10/site-packages/vulcan/_account.py", line 52, in register
    response = await api.post(full_url, body)
  File "/usr/local/lib/python3.10/site-packages/vulcan/_api.py", line 165, in post
    return await self._request("POST", url, body, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/vulcan/_api.py", line 126, in _request
    response = await r.json()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://lekcjaplus.vulcan.net.pl/gxxxxxxz/api/mobile/register/new')

**Comment by mariuszxeno** [comment]
I haw the same problem as in the posts above.

**Comment by greengo1** [comment]
Same here, not working since last Friday

**Comment by Antoni-Czaplicki** [comment]
I'm working on it

**Comment by Antoni-Czaplicki** [comment]
it looks like vulcan is randomly showing ads as a response to API calls and that's what's causing the exception.

**Comment by greengo1** [comment]
limit amount of api queries limit maybe? once every 10+mins?

**Comment by LukaszBogus** [comment]
Antoni but will you manage it somehow?

**Comment by Antoni-Czaplicki** [comment]
right now we are hoping that vulcan will fix that as it looks like some problem with cache and it affects official app too

**Comment by mariuszxeno** [comment]
on the official yes but on the unofficial none, it works as it worked without problems.

https://github.com/wulkanowy/wulkanowy

**Comment by Antoni-Czaplicki** [comment]
I know, that's because Wulkanowy work's by scrapping website instead of using the API, to use that in integration it would require to create a brand new implementation from grounds

**Comment by mariuszxeno** [comment]
ok thanks for the clarification, I'm looking forward to the results of your work

**Comment by kbabik** [comment]
Seems to be back to normal, sensors are working again
![image](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/103383354/af29fcbd-c133-4b41-91ef-75c73e03cc4a)

**Comment by Antoni-Czaplicki** [comment]
Yeah, can confirm - Vulcan fixed their cache issue

**Comment by mariuszxeno** [comment]
It's too early to be optimistic ?
![vul](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/106819738/623b25e8-416b-47ab-b0da-58d649f1912b)

**Comment by Antoni-Czaplicki** [comment]
It looks like a planed maintenance https://www.vulcan.edu.pl/aktualnosci/planowana-przerwa-techniczna-w-e-dzienniku-uonet-529

**Comment by casper255** [comment]
Is anything known?  The sensors work normally but there is still a problem with the calendar.

**Comment by Antoni-Czaplicki** [comment]
Hi, please check if the issue still exists
