### ISSUE TITLE
Integration not starting

### ISSUE THREAD

**Issue by Antoni-Czaplicki** [Antoni-Czaplicki/vulcan-for-hassio#52]
It doesn't work for me either, despite reinstallations and reboots, error log below:

2024-02-12 12:39:39.907 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *********** for vulcan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/vulcan/__init__.py", line 28, in async_setup_entry
await client.select_student()
File "/usr/local/lib/python3.12/site-packages/vulcan/_client.py", line 42, in select_student
students = await self.get_students()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/vulcan/_client.py", line 61, in get_students
self._students = await Student.get(self._api)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/vulcan/model/_student.py", line 79, in get
return [Student.load(student) for student in data]
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/vulcan/model/_serializable.py", line 49, in load
return to_model(cls, data)
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/related/functions.py", line 104, in to_model
value = cls(**value)
^^^^^^^^^^^^
File "<attrs generated init vulcan.model._student.Student>", line 11, in __init__
__attr_validator_class_(self, __attr_class_, self.class_)
File "/usr/local/lib/python3.12/site-packages/attr/validators.py", line 106, in __call__
raise TypeError(
TypeError: ("'class_' must be (<class 'str'>,) (got None that is a <class 'NoneType'>).", Attribute(name='class_', default=NOTHING, validator=<instance_of validator for type (<class 'str'>,)>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({'key': 'ClassDisplay'}), type=<class 'str'>, converter=<function str_if_not_none at 0x7f12484ce0c0>, kw_only=False, inherited=False, on_setattr=None, alias='class_'), (<class 'str'>,), None)

_Originally posted by @tomekswx in https://github.com/Antoni-Czaplicki/vulcan-for-hassio/issues/50#issuecomment-1938524327_

**Comment by Antoni-Czaplicki** [comment]
We are waiting for new vulcan-api release: https://github.com/kapi2289/vulcan-api/pull/138

**Comment by Antoni-Czaplicki** [comment]
https://github.com/Antoni-Czaplicki/vulcan-for-hassio/releases/tag/0.16.1
