### ISSUE TITLE
Problem z rejestracją "nowego" ucznia

### ISSUE THREAD

**Issue by tiwek** [Antoni-Czaplicki/vulcan-for-hassio#58]
Witam.

Jakiś czas (2 tygodnie) temu przestałą mi działać integracja, ale to nie pierwszy raz, więc usunąłem i chciałem dodać jak zwykle ale po wpisaniu danych mam error.

Na stronie nowe urządzenie się dodaje ale HA niestety rzuca błędem.

![Zrzut ekranu z 2024-04-11 08-35-03](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/74269691/7a35311d-32a7-4013-9fbc-900789b3423a)

```
Rejestrator: aiohttp.server
Źródło: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
Pierwsze zdarzenie: 08:34:23 (1 zdarzenia)
Ostatnio zalogowany: 08:34:23

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 356, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 402, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 506, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vulcan/config_flow.py", line 95, in async_step_auth
    students = await client.get_students()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vulcan/_client.py", line 61, in get_students
    self._students = await Student.get(self._api)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vulcan/model/_student.py", line 79, in get
    return [Student.load(student) for student in data]
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vulcan/model/_serializable.py", line 49, in load
    return to_model(cls, data)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/related/functions.py", line 104, in to_model
    value = cls(**value)
            ^^^^^^^^^^^^
  File "<attrs generated init vulcan.model._student.Student>", line 11, in __init__
    __attr_validator_class_(self, __attr_class_, self.class_)
  File "/usr/local/lib/python3.12/site-packages/attr/validators.py", line 106, in __call__
    raise TypeError(
TypeError: ("'class_' must be (<class 'str'>,) (got None that is a <class 'NoneType'>).", Attribute(name='class_', default=NOTHING, validator=<instance_of validator for type (<class 'str'>,)>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({'key': 'ClassDisplay'}), type=<class 'str'>, converter=<function str_if_not_none at 0x7fb267693d80>, kw_only=False, inherited=False, on_setattr=None, alias='class_'), (<class 'str'>,), None)
```

**Comment by Antoni-Czaplicki** [comment]
Duplikat #52
