### ISSUE TITLE
 TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'

### ISSUE THREAD

**Issue by majkers** [Antoni-Czaplicki/vulcan-for-hassio#62]
Mam taki błąd w logach:

```
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'
2024-12-16 09:05:46.145 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.latest_attendance_x_y fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/vulcan/sensor.py", line 383, in async_update
    and self.old_att < self.latest_attendance["datetime"]
```

**Comment by Antoni-Czaplicki** [comment]
Obawiam się że to może być ciężkie do zrobienie - błędy te najczęściej są spowodowane tym że vulcan coś zmienia w API a jakby je po prostu ignorować to nie byłoby widać że coś jest nie tak i de facto tego naprawić. Po to właśnie są logi

**Comment by Wielebny666** [comment]
Wiem, ze zaraz koniec roku szkolnego, ale up ;-)

**Comment by Antoni-Czaplicki** [comment]
Niestety integracja nie będzie już dużej rozwijana, zgłoszenie nie zostanie więc rozwiązane
