### ISSUE TITLE
Error while setting up vulcan platform for sensor

### ISSUE THREAD

**Issue by IT-freak-Jake** [Antoni-Czaplicki/vulcan-for-hassio#9]
Hi, I would like to use your integration but my HA gets an error when setting up Vulcan. I'm using the newest version of HA on raspberry pi 4 with 4GB RAM. Integration was installed by HACS. I can set up integration but after it, I don't get any entities, and in the logs, I have this information

Logger: homeassistant.components.sensor
Source: custom_components/vulcan/get_data.py:24
Integration: Sensor (documentation, issues)
First occurred: 9:01:44 PM (1 occurrences)
Last logged: 9:01:44 PM

Error while setting up vulcan platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/vulcan/sensor.py", line 30, in async_setup_entry
    hass.data[DOMAIN]["lessons"] = await get_lesson_info(
  File "/config/custom_components/vulcan/get_data.py", line 24, in get_lesson_info
    temp_dict["room"] = Lesson.room.code
AttributeError: 'NoneType' object has no attribute 'code'

**Comment by Antoni-Czaplicki** [comment]
Try to update to the latest version (0.8.4)

**Comment by IT-freak-Jake** [comment]
Unfortunately, it didn't change anything. I even tried to delete the integration, ".vulcan" folder and reinstall the integration

**Comment by Antoni-Czaplicki** [comment]
Can you submit a bug from the latest version? should be a little bit different.

**Comment by IT-freak-Jake** [comment]
Logger: homeassistant.components.sensor
Source: custom_components/vulcan/get_data.py:130
Integration: Sensor (documentation, issues)
First occurred: 12:42:17 PM (1 occurrences)
Last logged: 12:42:17 PM

Error while setting up vulcan platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/vulcan/sensor.py", line 37, in async_setup_entry
    hass.data[DOMAIN]["grade"] = await get_latest_grade(
  File "/config/custom_components/vulcan/get_data.py", line 130, in get_latest_grade
    async for grade in await client.data.get_grades():
  File "/usr/local/lib/python3.8/site-packages/vulcan/hebe/data/_grade.py", line 117, in get
    yield Grade.load(grade)
  File "/usr/local/lib/python3.8/site-packages/vulcan/hebe/model/_serializable.py", line 49, in load
    return to_model(cls, data)
  File "/usr/local/lib/python3.8/site-packages/related/functions.py", line 104, in to_model
    value = cls(**value)
  File "<attrs generated init vulcan.hebe.data._grade.Grade>", line 12, in __init__
    _setattr('column', __attr_converter_column(column))
  File "/usr/local/lib/python3.8/site-packages/related/converters.py", line 40, in __call__
    return to_model(self.cls, value)
  File "/usr/local/lib/python3.8/site-packages/related/functions.py", line 104, in to_model
    value = cls(**value)
  File "<attrs generated init vulcan.hebe.data._grade.GradeColumn>", line 24, in __init__
    __attr_validator_category(self, __attr_category, self.category)
  File "/usr/local/lib/python3.8/site-packages/attr/validators.py", line 35, in __call__
    raise TypeError(
TypeError: ("'category' must be <class 'vulcan.hebe.data._grade.GradeCategory'> (got None that is a <class 'NoneType'>).", Attribute(name='category', default=NOTHING, validator=<instance_of validator for type <class 'vulcan.hebe.data._grade.GradeCategory'>>, repr=True, eq=True, order=True, hash=None, init=True, metadata=mappingproxy({'key': 'Category'}), type=<class 'vulcan.hebe.data._grade.GradeCategory'>, converter=<related.converters.to_child_field.<locals>.ChildConverter object at 0x7f818b5100>, kw_only=False), <class 'vulcan.hebe.data._grade.GradeCategory'>, None)

**Comment by Antoni-Czaplicki** [comment]
This issue is API related, we are currently waiting for a new version to be released.

**Comment by Antoni-Czaplicki** [comment]
Ok, please try to update to the latest version (0.8.5) - it should fix that problem.

**Comment by IT-freak-Jake** [comment]
Everything is working now. Thank you!
